# Generated by Django 4.1.2 on 2022-11-15 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myownsite', '0002_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(choices=[('math', 'Математика'), ('phys', 'Физика'), ('russ', 'Русский язык'), ('it', 'Информатика')], default='math', max_length=4)),
                ('number', models.IntegerField()),
                ('ave_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('kabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myownsite.kabinet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
